name: Run Script

on:
  push:
    if: contains(github.event.head_commit.message, 'data update')
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'
jobs:

  create:
    name: create dataset
    runs-on: ubuntu-latest
    # if: ${{false}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: clean dir
        run: |
          git rm data/*
          mkdir data
          ls data
      - name: Run script
        run: |
          python scripts/create_dataset.py
          ls data
      - name: check if successful, then commit
        run: |
          if [ -f done ]; then
            echo "generated dataset successfully"
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add -A data/*
            git commit -m "updated data"
            git push
          else
            echo "failed to generate dataset"
          fi
